//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Administrator
    {
        public int IDAdmin { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone_Admin { get; set; }
        public string PasswordAdmin { get; set; }
        [NotMapped]
        [Compare("PasswordAdmin", ErrorMessage = "Mật khẩu không trùng khớp")]
        [Display(Name = "Xác nhận mật khẩu")]
        public string ConfirmPassword { get; set; }
        [NotMapped]
        public string LogInErrorMessage { get; set; }
        public Nullable<int> IDRole { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
