//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestSeller_1
    {
        public int IDProduct { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Gia { get; set; }
        public string Images { get; set; }
        public Nullable<int> BestSell { get; set; }
        public Nullable<int> ThuVe { get; set; }
    }
}
