//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopThu
    {
        public int IDHopThu { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public string Email { get; set; }
        public string SendText { get; set; }
    }
}
