//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InCome
    {
        public int IDInCome { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> IDOrderDetail { get; set; }
        public Nullable<int> Quanity { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Order Order { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
