//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int IDLienHe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public Nullable<System.DateTime> NgayLienHe { get; set; }
        public string ChuDe { get; set; }
        public string Status { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
